apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "neeleshapptest477"
  description: "neeleshapptest477"
  labels:
    system: web-apps
  links:
    - url: https://github.com/RohanAwasthi/neeleshapptest477
      title: "neeleshapptest477"
      icon: code
  tags:
    - java
    - azure
    - applicationtype-webapplication
  annotations:
    jenkins.io/github-folder: 'apache-azure-app/neeleshapptest477'
    jenkins.io/job-full-name: 'apache-azure-app/neeleshapptest477'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug:  RohanAwasthi/neeleshapptest477
    backstage.io/linguist: https://github.com/RohanAwasthi/neeleshapptest477
    azure.com/tag-selector: 'pid/neeleshapptest477'
spec:
  type: service
  lifecycle: development
  owner: user:default/neelesh.shekhar
